apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-{{ .Values.envName }}-dsg
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: efs-pv-{{ .Values.envName }}-dsg
  storageClassName: efs-sc
  volumeMode: Filesystem
