apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-deploy-pod-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
