apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-events-binding
subjects:
  - kind: ServiceAccount
    name: argo-events-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: create-deploy-pod-role
